### ISSUE TITLE
Unable to start the application

### ISSUE THREAD

**Issue by tomas321** [brewmajsters/brewmaster-backend#4]
After following the installation steps I get the following error:

```
root@instance-backend:/# /usr/bin/python3.7 /backend/wsgi.py
Traceback (most recent call last):
  File "/backend/wsgi.py", line 5, in <module>
    app = create_app()
  File "/backend/application.py", line 20, in create_app
    initialize_db(app)
  File "/backend/core/models/abstract/base_model.py", line 13, in initialize_db
    db.create_all()
  File "/usr/local/lib/python3.7/dist-packages/flask_sqlalchemy/__init__.py", line 1033, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/usr/local/lib/python3.7/dist-packages/flask_sqlalchemy/__init__.py", line 1025, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/usr/local/lib/python3.7/dist-packages/flask_sqlalchemy/__init__.py", line 956, in get_engine
    return connector.get_engine()
  File "/usr/local/lib/python3.7/dist-packages/flask_sqlalchemy/__init__.py", line 559, in get_engine
    sa_url = make_url(uri)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/url.py", line 229, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/url.py", line 288, in _parse_rfc1738_args
    return URL(name, **components)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/url.py", line 71, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: 'None'
```

Are you aware of this error?

**Comment by zurek11** [comment]
Did you create .env file from .env.example? This error is probably caused by missing port environment variable.

**Comment by tomas321** [comment]
Yes I have, and I suppose that would be caught by the `load_dotenv` call. Can you please verify this behaviour in your environment?

**Comment by tomas321** [comment]
Yes I have, and I suppose that would be caught by the `load_dotenv` call. Can you please verify this behaviour in your environment?

**Comment by tomas321** [comment]
I have solve my problem, sorry for the trouble. The problem was in not specifying the working directory.
